forum/config/routes.rb
DmForum::Engine.routes.draw do
  #--- for some reason, just having this in the main app's routes didn't work, so also added here
  themes_for_rails

  scope ":locale" do
    namespace :admin do
      get   '/dashboard/widget_forum_comments(/:comment_day)', controller: 'dashboard', action: :widget_forum_comments, as: :widget_forum_comments
      scope 'fms' do
        resource  :forum_site
        post '/forum_categories/sort', controller: 'forum_categories', action: :sort, as: :forum_category_sort
        resources :forum_categories do
          resources :forums
        end
        post '/forums/sort', controller: 'forums', action: :sort, as: :forum_sort
        resources :forums do
          member do
            get     'forum_users',          action: :forum_users, as: :forum_users
            match   'forum_add_member',     action: :forum_add_member, as: :forum_add_member, via: [:get, :post]
            delete  'forum_delete_member',  action: :forum_delete_member, as: :forum_delete_member
          end
        end
      end
    end

    scope 'forum' do
      get '/',                            controller: 'forums', action: :categories, as: :forum_root
      get '/:id',                         controller: 'forums', action: :show, as: :forum_show
      resources :forums do
        resources :forum_topics do
          resources :forum_comments
          patch 'toggle_follow', action: :toggle_follow
        end
        resources :posts
      end

      resources :forum_comments do
        get :search, on: :collection
      end
    end
  end
end

forum/app/controllers/dm_forum/admin/admin_controller.rb
class DmForum::Admin::AdminController < DmCore::Admin::AdminController
  before_action :authorize_access

  protected

  #------------------------------------------------------------------------------
  def authorize_access
    unless can?(:manage_forums, :all)
      flash[:alert] = "Unauthorized Access!"
      redirect_to current_account.index_path
    end
  end
end

forum/app/controllers/dm_forum/admin/dashboard_controller.rb
class DmForum::Admin::DashboardController < DmForum::Admin::AdminController
  #------------------------------------------------------------------------------
  def widget_forum_comments
    @comment_day = params[:comment_day].to_i
    respond_to do |format|
      format.html
      format.js
    end
  end
end

forum/app/controllers/dm_forum/admin/forum_categories_controller.rb
class DmForum::Admin::ForumCategoriesController < DmForum::Admin::AdminController
  include DmForum::PermittedParams

  before_action   :check_forum_site,  only:   [:index]
  before_action   :category_lookup,   except: [:index, :new, :create]

  # GET /admin/forum_categories
  #------------------------------------------------------------------------------
  def index
    @forum_categories = ForumCategory.includes(:translations).ordered
  end

  # GET /admin/forum_categories/1
  #------------------------------------------------------------------------------
  def show; end

  # GET /admin/forum_categories/new
  #------------------------------------------------------------------------------
  def new
    @forum_category = ForumCategory.new
  end

  # GET /admin/forum_categories/1/edit
  #------------------------------------------------------------------------------
  def edit; end

  # POST /admin/forum_categories
  #------------------------------------------------------------------------------
  def create
    @forum_category = ForumCategory.new(forum_category_params)

    if @forum_category.save
      redirect_to admin_forum_category_url(@forum_category), notice: 'Forum Category was successfully created.'
    else
      render action: :new
    end
  end

  # PUT /admin/forum_categories/1
  #------------------------------------------------------------------------------
  def update
    if @forum_category.update(forum_category_params)
      redirect_to admin_forum_category_url(@forum_category), notice: 'Forum Category was successfully updated.'
    else
      render action: :edit
    end
  end

  # DELETE /admin/forum_categories/1
  #------------------------------------------------------------------------------
  def destroy
    @forum_category.destroy

    redirect_to admin_forum_categories_url
  end

  #------------------------------------------------------------------------------
  def sort
    @forum_category.update_attribute(:row_order_position, params[:item][:row_order_position])

    #--- this action will be called via ajax
    head :ok
  end

  private

  # make sure a ForumSite singleton is created
  #------------------------------------------------------------------------------
  def check_forum_site
    ForumSite.create(enabled: true) unless ForumSite.site
  end

  #------------------------------------------------------------------------------
  def category_lookup
    @forum_category = ForumCategory.find(params[:id])
  end
end

forum/app/controllers/dm_forum/admin/forum_sites_controller.rb
# This controller is now deprecated.  At the moment I find no use
# for the enableg, tagline, or description.
#------------------------------------------------------------------------------
class DmForum::Admin::ForumSitesController < DmForum::Admin::AdminController
  include DmForum::PermittedParams

  before_action :forum_site_lookup

  # GET /admin/fms/forum_site
  #------------------------------------------------------------------------------
  def show
    @forum_site ||= ForumSite.create(enabled: true)
  end

  # GET /admin/fms/forum_site/edit
  #------------------------------------------------------------------------------
  def edit; end

  # PUT /admin/fms/forum_site
  #------------------------------------------------------------------------------
  def update
    if @forum_site.update(forum_site_params)
      redirect_to dm_forum.admin_forum_site_url, notice: "Forum settings were successfully updated."
    else
      render action: :edit
    end
  end

  private

  #------------------------------------------------------------------------------
  def forum_site_lookup
    @forum_site = ForumSite.site
  end
end

forum/app/controllers/dm_forum/admin/forums_controller.rb
class DmForum::Admin::ForumsController < DmForum::Admin::AdminController
  include DmForum::PermittedParams

  before_action   :category_lookup, only: [:index, :new, :create]
  before_action   :forum_lookup,    except: [:index, :new, :create]
  # before_action   :set_title

  # GET /admin/fms/forums
  #------------------------------------------------------------------------------
  def index
    if ForumSite.first
      @forums = @forum_category.forums.ordered
    else
      redirect_to admin_forum_site_path, notice: "Please configure the Forum system first"
    end
  end

  #------------------------------------------------------------------------------
  def show; end

  # GET /admin/fms/forums/new
  #------------------------------------------------------------------------------
  def new
    @forum = @forum_category.forums.build
  end

  # GET /admin/fms/forums/1/edit
  #------------------------------------------------------------------------------
  def edit; end

  # POST /admin/fms/forums
  #------------------------------------------------------------------------------
  def create
    @forum = @forum_category.forums.new(forum_params)
    @forum.forum_site = ForumSite.site

    if @forum.save
      redirect_to admin_forum_category_url(@forum_category), notice: 'Forum was successfully created.'
    else
      render action: :new
    end
  end

  # PUT /admin/fms/forums/1
  #------------------------------------------------------------------------------
  def update
    if @forum.update(forum_params)
      redirect_to admin_forum_url(@forum), notice: 'Forum was successfully updated.'
    else
      render action: :edit
    end
  end

  # DELETE /admin/fms/forums/1
  #------------------------------------------------------------------------------
  def destroy
    @forum.destroy

    redirect_to admin_forum_category_url(@forum.forum_category)
  end

  #------------------------------------------------------------------------------
  def sort
    @forum.update_attribute(:row_order_position, params[:item][:row_order_position])

    #--- this action will be called via ajax
    head :ok
  end

  #------------------------------------------------------------------------------
  def forum_users
    respond_to do |format|
      format.json { render json: ForumUserDatatable.new(view_context, @forum) }
    end
  end

  # Add user(s) to forum.
  # => user_id: add a single user
  #------------------------------------------------------------------------------
  def forum_add_member
    if !params[:user_id].blank?
      user = User.find(params[:user_id])
      @forum.add_member(user)
      redirect_to admin_forum_url(@forum), notice: "Forum access granted for #{user.full_name}"
    else
      redirect_to admin_forum_url(@forum), alert: "Incorrect parameters supplied"
    end
  end

  #------------------------------------------------------------------------------
  def forum_delete_member
    user = User.find(params[:user_id])
    @forum.remove_member(user)
    redirect_to admin_forum_url(@forum), notice: "Forum access removed for #{user.full_name}"
  end

  private

  #------------------------------------------------------------------------------
  def category_lookup
    @forum_category = ForumCategory.find(params[:forum_category_id])
  end

  #------------------------------------------------------------------------------
  def forum_lookup
    @forum = Forum.friendly.find(params[:id])
    @forum_category = @forum.forum_category
  end
end

forum/app/controllers/dm_forum/application_controller.rb
# Subclass from main ApplicationController, which will subclass from DmCore
#------------------------------------------------------------------------------
class DmForum::ApplicationController < ::ApplicationController
  include ApplicationHelper

  #--- these are needed to support rendering layouts built for the CMS
  helper    DmCms::RenderHelper
  helper    DmCore::LiquidHelper
  helper    DmCms::PagesHelper
  include   DmCore::RenderHelper

  # before_action :authenticate_user!

  layout    'forum_templates/forum_list'

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  #------------------------------------------------------------------------------
  def record_not_found
    flash[:error] = "The forum or discussion you were looking for could not be found."
    redirect_to forum_root_path
  end
end

forum/app/controllers/dm_forum/forums_controller.rb
class DmForum::ForumsController < DmForum::ApplicationController
  include ApplicationHelper

  #--- these are needed to support rendering layouts built for the CMS
  helper  DmCms::RenderHelper
  helper  DmCore::LiquidHelper
  helper  DmCms::PagesHelper
  include DmCore::RenderHelper

  before_action :forum_lookup, except: [:list, :categories]
  layout 'forum_templates/forum_list', only: [:list, :show, :categories]

  #------------------------------------------------------------------------------
  def categories
    @forum_categories = ForumCategory.includes(:forums, :translations).ordered
  end

  # GET /forum
  #------------------------------------------------------------------------------
  def list
    @forums = Forum.available_to_user(current_user)
  end

  # GET /forum/:slug
  #------------------------------------------------------------------------------
  def show
    (session[:forums]       ||= {})[@forum.id] = Time.now.utc
    (session[:forums_page]  ||= Hash.new(1))[@forum.id] = page_number if page_number > 1
    @followed                 = user_signed_in? && params[:followed]
    @forum_topics           ||= @forum.forum_topics.includes(recent_comment: [{ user: [:user_profile] }], user: [:user_profile]).paginate page: page_number
    @followed_topics        ||= user_signed_in? ? (@forum.followed_topics(current_user).paginate page: page_number) : nil
  end

  protected

  #------------------------------------------------------------------------------
  def forum_lookup
    @forum = Forum.find_by_slug!(params[:id])
    authorize! :read, @forum
  end
end

forum/app/helpers/dm_forum/application_helper.rb
module DmForum
  module ApplicationHelper
    include ForumHelper
  end
end

forum/app/helpers/dm_forum/forum_helper.rb
module DmForum
  module ForumHelper
    #------------------------------------------------------------------------------
    def topic_title_link(topic, options)
      if topic.title =~ /^\[([^\]]{1,15})\]((\s+)\w+.*)/
        "<span class='flag'>#{Regexp.last_match(1)}</span>" +
          link_to(Regexp.last_match(2).strip, forum_forum_topic_path(@forum, topic), options)
      else
        link_to(topic.title, forum_forum_topic_path(@forum, topic), options)
      end
    end

    #------------------------------------------------------------------------------
    def modify_history(function, name, path, params_hash = nil)
      state = "null"
      query_string = "?"
      if params_hash
        state = params_hash.to_json
        params_hash.each { |k, v| query_string << "#{k}=#{v}&" }
      end
      query_string = query_string.chop
      %{history.#{function}(#{state}, '#{j(name)}', '#{j(path + query_string)}');}.html_safe
    end

    #------------------------------------------------------------------------------
    def edited_on_tag(post)
      %(<span class='date'>#{I18n.t 'fms.post_edited', when: time_ago_in_words(post.updated_at)}</span>).html_safe if post.updated_at - post.created_at > 5.minutes
    end

    # used to know if a topic has changed since we read it last
    #------------------------------------------------------------------------------
    def recent_topic_activity(topic)
      return false unless user_signed_in?

      topic.last_updated_at > ((session[:forum_topics] ||= {})[topic.id] || last_active)
    end

    # used to know if a forum has changed since we read it last
    #------------------------------------------------------------------------------
    def recent_forum_activity(forum)
      return false unless user_signed_in? && forum.recent_topic

      forum.recent_topic.last_updated_at > ((session[:forums] ||= {})[forum.id] || last_active)
    end

    #------------------------------------------------------------------------------
    def last_active
      session[:last_active] ||= Time.now.utc
    end

    # Ripe for optimization
    #------------------------------------------------------------------------------
    def voice_count
      pluralize ForumSite.site.forum_topics.to_a.sum(&:voice_count), 'voice'
    end

    #------------------------------------------------------------------------------
    def feed_icon_tag(title, url)
      # (@feed_icons ||= []) << { :url => url, :title => title }
      # link_to image_tag('feed-icon.png', :size => '14x14', :alt => "Subscribe to #{title}"), url
    end

    #------------------------------------------------------------------------------
    def forum_crumbs(forum = nil)
      seperator  = "<span class='arrow'><i class='fa fa-angle-right'></i></span>".html_safe
      out        = "".html_safe
      out       += link_to(I18n.t('fms.forums'), forum_root_path) + seperator
      if forum
        out     += link_to(forum.name, forum_path(forum))
        page     = session[:forum_page] ? session[:forum_page][forum.id] : nil
        if page && (page != 1)
          out   += "<small style='color:#ccc'>(".html_safe
          out   += link_to(I18n.t('fms.page_nr'), forum_path(id: forum, page: page))
          out   += ")</small>".html_safe
        end
        out += seperator
      end
      out
    end

    #------------------------------------------------------------------------------
    def forum_topic_icon(forum_topic)
      if recent_topic_activity(forum_topic)
        style       = "style='color:green'"
        recent_txt  = I18n.t('fms.views_forums.recent_activity')
      else
        style       = ''
        recent_txt  = I18n.t('fms.views_forums.no_recent_activity')
      end
      if forum_topic.locked?
        "<i class='fa fa-lock fa-lg' #{style} title='#{I18n.t('fms.views_forums.comma_locked_topic')}'></i>".html_safe
      else
        "<i class='fa fa-comments fa-lg' #{style} title='#{recent_txt}'></i>".html_safe
      end
    end

    #------------------------------------------------------------------------------
    def forum_comment_user_state(forum_comment)
      if forum_comment.user.is_admin?
        I18n.t 'fms.user_is_administrator', default: 'Administator'
      elsif can?(:moderate, forum_comment.forum_topic.forum)
        I18n.t 'fms.user_is_moderator', default: 'Moderator'
      elsif forum_comment.user.suspended?
        forum_comment.user.state
      end
    end
  end
end

forum/app/views/dm_forum/forum_topics/_comment_item.html.erb
<li class="clearfix" id="<%= dom_id(comment_item) %>">
  <div class="user"><%= avatar_for comment_item.user, 48 %></div>
  <p class="comment_author"><%= truncate(comment_item.user.display_name, :length => 30) %>
    <% if false #can?(:moderate, comment_item.forum_topic.forum) || !comment_item.user.active? %>
      <span class="admin">(<%= forum_comment_user_state(comment_item) %>)</span>
    <% end %>
  </p>
  <p class="info">
    <%= present(comment_item).date_posted %>
    <% edited = edited_on_tag(comment_item) %>
    <%= " | #{edited}".html_safe if edited %>
    <%= ' | '.html_safe + link_to(I18n.t('fms.reply'), '#reply') unless @forum_topic.locked? || !user_signed_in? %>
    <% if user_signed_in? && can?(:edit, comment_item) %>
    |
      <%= link_to I18n.t('fms.admin.edit_post'), edit_forum_forum_topic_forum_comment_path(@forum, @forum_topic, comment_item), :class => 'utility' %>
    <% end %>
  </p>
  <div class="clearfix"></div>
  <div class="comment_text">
    <% if comment_item.user.active? %>
      <%= present(comment_item).formatted_comment %>
    <% else %>
      <p>(<% I18n.t 'fms.suspended_user_post' %>)</p>
    <% end %>
  </div>
</li>

forum/app/views/dm_forum/forum_topics/_comments_list.html.erb
<a name="<%= dom_id @forum_comments.first %>" id="<%= dom_id @forum_comments.first %>">&#xA0;</a>

<div id="comment_section">
  <% if @forum_comments.first.is_root? %>
    <div class="comments clearfix">
      <ul class="comment_list first_comment">
        <%= render(:partial => 'comment_item', object: @forum_comments.first) %>
      </ul>
    </div>
  <% end %>

  <div class="comment_section_header">
    <div class="num_comments"> <%= "#{@forum_comments.count - 1} #{I18n.t 'cms.comments_stat'}" %></div>
    <% if user_signed_in? and !@forum_topic.locked? %>
      <div class="reply_link"><%= link_to I18n.t('fms.reply_to_topic'), "#reply" %></div>
    <% end %>
    <div class="comment_pagination"><%= pagination(@forum_comments) %></div>
  </div>


  <div class="comments clearfix">
    <ul class="comment_list">
      <% for forum_comment in @forum_comments do %>
        <%= render(:partial => 'comment_item', object: forum_comment) unless forum_comment.is_root? %>
      <% end %>
      <% if current_user %>
        <li class="clearfix" id="reply">
          <% if !@forum_topic.locked? %>
            <div class="user"><%= avatar_for current_user, 50 %></div>
            <div class="reply_field">
              <%= simple_form_for [@forum, @forum_topic, @forum_topic.forum_comments.new] do |f| %>
                <%= f.text_area :body, rows: 5, placeholder: I18n.t('cms.add_comment') %>
                <div class="comment_formatting_hint">
                  <%= nls :comment_extra_instruction %>
                  <%= I18n.t('fms.comment_notification_inform')%>
                </div>
                <%= f.submit I18n.t('fms.views_topics.save_reply'), class: 'btn btn-primary' %>
              <% end %>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

<% if @forum_topic.locked? %>
  <div class="topic_locked_message">
    <p class="topic_locked"><%= I18n.t 'fms.views_topics.locked_topic' %></p>
  </div>
<% elsif !current_user %>
  <p><%= I18n.t 'cms.comment_login_required' %></p>
  <div class="login_required_buttons">
    <%= link_to I18n.t('core.login'), main_app.new_user_session_path(redirect_to: request.url), class: 'btn btn-primary' %>
    <%= link_to I18n.t('core.create_account'), main_app.new_user_registration_path, class: 'btn'  %>
  </div>
<% end %>


  <div class="comment_section_footer">
    <div class="comment_pagination"><%= pagination(@forum_comments) %></div>
  </div>
</div>
<div class="clear"></div>

forum/app/views/dm_forum/forum_topics/_follow_button.html.erb
<% button_title = following ? I18n.t('fms.follow_stop') : I18n.t('fms.follow') %>
<% follow_class = following ? 'btn btn-default btn-small follow_active' : 'btn btn-default btn-small' %>
<%= button_to button_title, forum_forum_topic_toggle_follow_path(@forum, @forum_topic.id), remote: true, method: :patch, id: 'follow_button', class: follow_class %>

forum/app/views/dm_forum/forum_topics/_form.html.erb
<%= simple_form_for [@forum, @forum_topic], wrapper: simple_form_theme_wrapper do |f| %>

  <%= f.error_notification :message => "Please review the problems below" %>
  <%= f.input :title, :label => I18n.t('fms.views_topics.topic') %>

  <% if @forum_topic.new_record? %>
    <%= f.input :body, :as => :text, :label => I18n.t('fms.views_topics.body'), :input_html => {:rows => 10} %>
  <% elsif is_admin? %>
    <%= f.input :forum_id, collection: ForumSite.site.all_forums, label_method: :name, value_method: :id %>
  <% end %>

  <% if can? :moderate, @forum %>
    <div class="clearfix">
      <%= f.input :sticky, :label => "<i class='fa fa-thumb-tack'></i> #{I18n.t('fms.sticky')}".html_safe %>
    </div>
    <div class="clearfix">
      <%= f.input :locked, :label => "<i class='fa fa-lock'></i> #{I18n.t('fms.views_topics.lock_topic')}".html_safe %>
    </div>
  <% end %>

  <%= f.submit I18n.t('fms.post_topic'), class: 'btn btn-primary' %>
  <%#= submit_or_cancel :save => I18n.t('fms.post_topic'), :cancel => I18n.t('fms.views_topics.cancel'),
            :cancel_url => (@forum_topic.new_record? ? [@forum] : [@forum, @forum_topic]) %>
<% end %>

forum/app/views/dm_forum/forum_topics/edit.html.erb
<% content_for :page_title, @forum.forum_category.name %>
<% content_for :sidebar do %>
  <%= render :partial => "dm_forum/forum_comments/formatting" %>
<% end %>

<% content_for :crumbs, forum_crumbs(@forum_topic.forum) %>

<%= render(:partial => 'dm_forum/forums/forum_header', :object => @forum, :as => :forum) %>

<h1 id="new_topic"><%= I18n.t 'fms.edit_topic' %></h1>
<p class="subtitle"><%= I18n.t 'fms.by_user', :user => current_user.display_name %></p>

<%= render :partial => "form" %>

forum/app/views/dm_forum/forum_topics/new.html.erb
<% content_for :page_title, @forum.forum_category.name %>
<% content_for :sidebar do %>
  <%= render :partial => "dm_forum/forum_comments/formatting" %>
<% end %>

<% content_for :crumbs, forum_crumbs(@forum_topic.forum) %>

<%= render(:partial => 'dm_forum/forums/forum_header', :object => @forum, :as => :forum) %>

<h1 id="new_topic"><%= I18n.t 'fms.new_topic' %></h1>
<p class="subtitle"><%= I18n.t 'fms.by_user', :user => current_user.display_name %></p>

<%= render :partial => "form" %>

forum/app/views/dm_forum/forum_topics/show.html.erb
<% content_for :page_title, @forum_topic.title %>

<% content_for :sidebar do %>

  <%= render(partial: 'dm_forum/forum_topics/follow_button', locals: {following: @following} ) if current_user %>
  <div class="clear"></div>
  <div class="forum_sidebar_voices">
    <h5><%= I18n.t 'fms.voices' %></h5>
    <ul>
      <% @forum_topic.voices.each do |user| %>
        <li><%= user.display_name %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% content_for :crumbs, forum_crumbs(@forum_topic.forum) %>

<div class="comment_section" id="comment_section">

  <%= render(partial: 'dm_forum/forums/forum_header', object: @forum_topic.forum, as: :forum) %>

  <h1 id="topic_title">
    <%= @forum_topic.title %>
    <% if @forum_topic.locked? %>
      <span>(<%= I18n.t 'fms.topic' %> <%= I18n.t 'fms.locked' %>)</span>
    <% end %>
    <% if user_signed_in? %>
      <% if can? :edit, @forum_topic %>
        <span id="topic_mod">
          <%= link_to(I18n.t('fms.edit'), edit_forum_forum_topic_path(@forum, @forum_topic), class: "utility") %>
          <% if is_admin? %>
            | <%= link_to(I18n.t('fms.delete'), forum_forum_topic_path(@forum, @forum_topic), class: "utility", method: :delete, data: {confirm: I18n.t('fms.views_topics.delete_sure')}) %>
          <% end %>
        </span>
      <% end %>
    <% end %>
  </h1>

  <p class="subtitle">
    <%= I18n.t 'fms.count_comments', count: @forum_topic.forum_comments.size - 1,
              num: number_with_delimiter(@forum_topic.forum_comments.size - 1) %>,
    <%= I18n.t 'fms.count_voices', count: @forum_topic.voices.size,
              num: number_with_delimiter(@forum_topic.voices.size) %>
  </p>

  <%= render(partial: 'comments_list') unless @forum_comments.empty?%>

</div>