newsletter/config/routes.rb
DmNewsletter::Engine.routes.draw do
  scope ":locale" do
    namespace :admin do
      scope 'nms' do
        patch '/newsletters/synchronize_lists', controller: :newsletters, action: :synchronize_lists
        resources :newsletters
      end
    end

    post   '/newsletter/subscribe_to_newsletter/:token',     controller: :newsletters, action: :subscribe_to_newsletter, as: :subscribe_to_newsletter
    delete '/newsletter/unsubscribe_from_newsletter/:token', controller: :newsletters, action: :unsubscribe_from_newsletter, as: :unsubscribe_from_newsletter
  end
end

newsletter/app/models/newsletter.rb
#------------------------------------------------------------------------------
class Newsletter < ApplicationRecord
  self.table_name = 'email_newsletters'

  # [todo] has_many                :newsletter_subscribers, :dependent => :destroy

  validates_uniqueness_of :token

  default_scope           { where(account_id: Account.current&.id) }
  before_create           :generate_token

  #------------------------------------------------------------------------------
  def subscribe(user_or_email, options = { FNAME: '', LNAME: '' }); end

  #------------------------------------------------------------------------------
  def update_list_stats; end

  #------------------------------------------------------------------------------
  def map_error_to_msg(code); end

  # Find the newsletter associated with the token
  #------------------------------------------------------------------------------
  def self.find_newsletter(token, options = {})
    Newsletter.find_by_token(token)
  end

  #------------------------------------------------------------------------------
  def self.signup_information(token, options = {}); end

  protected

  #------------------------------------------------------------------------------
  def generate_token
    self.token = loop do
      random_token = SecureRandom.hex(10)
      break random_token unless Newsletter.where(token: random_token).exists?
    end
  end
end

newsletter/app/controllers/dm_newsletter/admin/newsletters_controller.rb
class DmNewsletter::Admin::NewslettersController < DmNewsletter::Admin::AdminController
  include DmNewsletter::PermittedParams

  # before_action   :mailchimp_guard,   only:   [:new, :edit, :create, :update]
  before_action :newsletter_lookup, except: [:index, :new, :create, :synchronize_lists]

  #------------------------------------------------------------------------------
  def index
    @newsletters = using_mailchimp? ? MailchimpNewsletter.all : StandardNewsletter.all
    @newsletters.each(&:update_list_stats)
  end

  #------------------------------------------------------------------------------
  def new
    @newsletter = using_mailchimp? ? MailchimpNewsletter.new : StandardNewsletter.new
  end

  #------------------------------------------------------------------------------
  def edit; end

  #------------------------------------------------------------------------------
  def create
    @newsletter = using_mailchimp? ? MailchimpNewsletter.new(mailchimp_newsletter_params) : StandardNewsletter.new(standard_newsletter_params)
    if @newsletter.save
      redirect_to admin_newsletters_url, notice: 'Newsletter was successfully created.'
    else
      render action: :new
    end
  end

  #------------------------------------------------------------------------------
  def update
    if @newsletter.update(newsletter_params)
      redirect_to admin_newsletters_url, notice: 'Newsletter was successfully updated.'
    else
      render action: :edit
    end
  end

  #------------------------------------------------------------------------------
  def destroy
    @newsletter.destroy

    redirect_to admin_newsletters_url
  end

  #------------------------------------------------------------------------------
  def show
    # @subscriptions  = @newsletter.subscriptions
    @folder_list = @newsletter.folder_list
  end

  #------------------------------------------------------------------------------
  def synchronize_lists
    if using_mailchimp?
      MailchimpNewsletter.synchronize
      redirect_to(admin_newsletters_url, notice: 'Synchronized with Mailchimp') && return
    else
      redirect_to(admin_newsletters_url) && return
    end
  end

  private

  #------------------------------------------------------------------------------
  def newsletter_lookup
    @newsletter = Newsletter.find(params[:id])
  end

  # Protects certain actions from being run if we're using mailchimp integration
  #------------------------------------------------------------------------------
  def mailchimp_guard
    if using_mailchimp?
      redirect_to(admin_newsletters_url, error: 'Action not supported when using Mailchimp') && (return false)
    else
      true
    end
  end
end

newsletter/app/controllers/dm_newsletter/newsletters_controller.rb
class DmNewsletter::NewslettersController < DmNewsletter::ApplicationController
  # Handle a newsletter signup.  By submitting using a Rails form
  # and then adding via the MailChimp API, it should cut out automated signups
  # from spam bots, because the authenticity token will be validated first.
  #------------------------------------------------------------------------------
  def subscribe_to_newsletter
    subscription_params = params['subscription'] || {}
    user_or_email       = current_user ? current_user : subscription_params['email']
    @newsletter         = Newsletter.find_newsletter(params['token'])

    if @newsletter
      result = @newsletter.subscribe(user_or_email, subscription_params, new_subscription: !current_user.present?)

      respond_to do |format|
        if result[:success]
          msg = I18n.t('nms.subscription_successful')
          format.html { redirect_back fallback_location: main_app.index_url, notice: msg }
          format.json { render json: { success: true, msg: msg } }
        else
          msg = I18n.t(@newsletter.map_error_to_msg(result[:code]))
          format.html { redirect_back fallback_location: main_app.index_url, alert: msg }
          format.json { render json: { success: false, msg: msg } }
        end
      end
    end
  end

  # Unsubscribe current user from newsletter.  We only support direct unsubscribing
  # for a logged in user
  #------------------------------------------------------------------------------
  def unsubscribe_from_newsletter
    email       = current_user ? current_user.email : ''
    @newsletter = Newsletter.find_newsletter(params['token'])

    if @newsletter
      result = @newsletter.unsubscribe(email)
      respond_to do |format|
        if result
          msg = I18n.t('nms.unsubscribe_successuful')
          format.html { redirect_back fallback_location: main_app.index_url, notice: msg }
          format.json { render json: { success: true, msg: msg } }
        else
          msg = I18n.t('nms.Email_NotExists')
          format.html { redirect_back fallback_location: main_app.index_url, alert: msg }
          format.json { render json: { success: false, msg: msg } }
        end
      end
    end
  end
end

newsletter/app/helpers/dm_newsletter/newsletters_helper.rb
module DmNewsletter::NewslettersHelper
  #------------------------------------------------------------------------------
  def using_mailchimp?
    Account.current.preferred_nms_use_mailchimp?
  end
end

newsletter/app/views/dm_newsletter/admin/newsletters/_form.html.erb
<% submit_url = (@newsletter.new_record? ? admin_newsletters_path : admin_newsletter_path) %>
<%= simple_form_for @newsletter, url: submit_url,
      html: { class: 'form-horizontal' }, wrapper: :bs3_horizontal_form, wrapper_mappings: DmAdmin::FormWrapperMappings do |f| %>

  <%= f.error_notification :message => "Please review the problems below" %>

  <%= panel header: false do %>
    <% if using_mailchimp? %>
      <%= f.input :mc_id , label: 'List ID', hint: 'MailChimp List ID, in the "Settings -> List Name and Defatuls" setion of a list' %>
    <% else %>
      <%= f.input :name , label: 'Name of Newsletter' %>
    <% end %>

    <%= submit_or_cancel :cancel_url => admin_newsletters_path %>
  <% end %>

<% end %>

newsletter/app/views/dm_newsletter/admin/newsletters/edit.html.erb
<% content_for :content_title, "Edit Newsletter <small>#{@newsletter.name}</small>".html_safe %>
<%= render 'form' %>

newsletter/app/views/dm_newsletter/admin/newsletters/index.html.erb
<% content_for :content_title_extra do %>
  <%= page_header_buttons do %>
    <%= link_to(icon_label(:new, 'New'), new_admin_newsletter_path, title: 'New Newsletter', class: "btn btn-sm btn-default") %>
  <% end %>
<% end %>

<% if false #using_mailchimp? %>
  <% content_for :sidebar do %>
    <%= link_to 'Sync with Mailchimp', admin_newsletters_synchronize_lists_path, class: "action-button greyish" %>
  <% end %>
<% end %>


<% content_for :content_title, 'Newsletter Dashboard' %>

<% @newsletters.in_groups_of(2, false) do |newsletter_row| %>
  <div class="row">
    <% for newsletter in newsletter_row  %>
      <div class="col-md-12">
        <% toolbar = toolbar_btn(newsletter.subscribed_count, admin_newsletter_path(newsletter), title: 'Number of subscriptions', class: 'label label-success pull-right') %>
        <%= panel title: link_to(newsletter.name, admin_newsletter_path(newsletter)), toolbar: toolbar do %>
          <ul class="statistics">
            <% total = newsletter.subscribed_count + newsletter.unsubscribed_count + newsletter.cleaned_count %>
            <li><%= stat_block_small label: 'subscribed', number: newsletter.subscribed_count, icon: 'fa fa-info fa-fw', color_type: :success, percent: total == 0 ? 0 : (100 * newsletter.subscribed_count / total) %></li>
            <li><%= stat_block_small label: 'unsubscribed', number: newsletter.unsubscribed_count, icon: 'fa fa-info fa-fw', color_type: :danger, percent: total == 0 ? 0 : (100 * newsletter.unsubscribed_count / total) %></li>
            <li><%= stat_block_small label: 'cleaned', number: newsletter.cleaned_count, icon: 'fa fa-info fa-fw', color_type: :info, percent: total == 0 ? 0 : (100 * newsletter.cleaned_count / total) %></li>
          </ul>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

newsletter/app/views/dm_newsletter/admin/newsletters/new.html.erb
<% content_for :content_title, 'New Newsletter' %>
<%= render 'form' %>

newsletter/app/views/dm_newsletter/admin/newsletters/show.html.erb
<% content_for :content_title, "#{@newsletter.name} <small>Newsletter</small>".html_safe %>
<% content_for :content_title_extra do %>
  <%= page_header_buttons do %>
    <%= link_to(icon_label(:trash, 'Delete'), admin_newsletter_path(@newsletter), method: :delete, class: "btn btn-sm btn-default", data: {confirm: 'Are you sure you wish to delete this newsletter?'}) %>
  <% end %>
<% end %>

<%= panel header: false do %>
  <div class="row">
    <ul class="statistics">
      <% total = @newsletter.subscribed_count + @newsletter.unsubscribed_count + @newsletter.cleaned_count %>
      <li><%= stat_block_small label: 'subscribed', number: @newsletter.subscribed_count, color_type: :success, percent: total == 0 ? 0 : (100 * @newsletter.subscribed_count / total) %></li>
      <li><%= stat_block_small label: 'unsubscribed', number: @newsletter.unsubscribed_count, color_type: :danger, percent: total == 0 ? 0 : (100 * @newsletter.unsubscribed_count / total) %></li>
      <li><%= stat_block_small label: 'cleaned', number: @newsletter.cleaned_count, color_type: :info, percent: total == 0 ? 0 : (100 * @newsletter.cleaned_count / total) %></li>
    </ul>
    <hr>
  </div>

  <div class="row">
    <dl class="dl-horizontal">
      <dt>Subscription Token</dt>
      <dd><%= @newsletter.token %></dd>
    </dl>
  </div>
<% end %>

<%= panel body: false, title: 'Campaign Folders' do %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th width="50">Count</th>
        <th width="100">Folder ID</th>
      </tr>
    </thead>
    <tbody>
      <% @folder_list.each do |folder| %>
        <tr class="item">
          <td><%= folder[:name] %></td>
          <td><%= folder[:count] %></td>
          <td><%= folder[:id] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>