cms/config/routes.rb
DmCms::Engine.routes.draw do
  scope ":locale" do
    namespace :admin do
      patch '/cms_pages/expire_cache',                          controller: 'cms_pages', action: :expire_cache, as: :expire_cache
      patch '/cms_pages/expire_cache_total',                    controller: 'cms_pages', action: :expire_cache_total, as: :expire_cache_total
      post  '/cms_pages/ajax_sort',                             controller: 'cms_pages', action: :ajax_sort, as: :cms_page_sort
      get   '/dashboard/widget_blog_comments(/:comment_day)',   controller: 'dashboard', action: :widget_blog_comments, as: :widget_blog_comments
      resources :cms_pages do
        member do
          get   :new_page
          post  :create_page
          put   :duplicate_page
          post  :file_tree
          get   :file_tree
          match 'permissions',                           action: 'permissions', via: [:get, :post, :patch]
          match 'mark_welcome_page',                     action: 'mark_welcome_page', via: [:patch]
          patch 'ajax_toggle_permission/:user_id/:role', action: 'ajax_toggle_permission', as: 'ajax_toggle_permission'
        end
      end

      resources :cms_contentitems do
        member do
          get    :new_content
          post   :create_content
          get    :markdown
          post   :markdown
        end
      end
      post '/cms_contentitems/sort', controller: 'cms_contentitems', action: :sort, as: :cms_contentitem_sort
      resources :cms_snippets
      resources :cms_blogs do
        member do
          get     'blog_users',          action: :blog_users, as: :blog_users
          match   'blog_add_member',     action: :blog_add_member, as: :blog_add_member, via: [:get, :post]
          delete  'blog_delete_member',  action: :blog_delete_member, as: :blog_delete_member
          match   'permissions',         action: 'permissions', via: [:get, :post, :patch]
          patch   'ajax_toggle_permission/:user_id/:role', action: 'ajax_toggle_permission', as: 'ajax_toggle_permission'
        end
        resources :cms_posts do
          member do
            put 'send_notifications_emails', action: :send_notifications_emails, as: :send_notifications_emails
          end
        end
      end
      # resources :cms_posts do
      #   member do
      #     put     'send_notifications_emails',    action: :send_notifications_emails, as: :send_notifications_emails
      #   end
      # end
      post '/cms_blogs/sort', controller: 'cms_blogs', action: :sort, as: :cms_blog_sort
      resources :media_files
    end

    scope 'blog' do
      get   '/recent_posts',                      controller: 'blogs', action: :index, as: :blog_root
      get   '/:id',                               controller: 'blogs', action: :show, as: :blog_show
      get   '/:cms_blog_id/:id',                  controller: 'posts', action: :show, as: :post_show
      resources :cms_blogs do
        post    '/cms_posts/ajax_add_comment/:id', controller: 'posts', action: :ajax_add_comment, as: :cms_post_ajax_add_comment
        # get  '/cms_posts/ajax_edit_comment/:id', controller: 'posts', action: :ajax_edit_comment, as: :cms_postajax_edit_comment_comment
        resources :cms_posts
        patch 'toggle_follow', controller: 'blogs', action: :toggle_follow
      end
      resources :cms_posts do
        delete  'ajax_delete_comment/:id', controller: 'posts', action: :ajax_delete_comment, as: :ajax_delete_comment_comment
      end
    end

    post  '/contact_form/create',                 controller: :contact_form, action: :create, as: :create_contact_form
    get   '/coming_soon',                         controller: 'pages', action: :show, slug: 'coming_soon', as: :coming_soon
    get   '/*slug(/:xaction(/:xid))',             controller: 'pages', action: :show, as: :showpage # use *slug to fix this https://github.com/rails/rails/issues/16058
  end
end

cms/app/controllers/dm_cms/admin/cms_pages_controller.rb
class DmCms::Admin::CmsPagesController < DmCms::Admin::AdminController
  include DmCms::PermittedParams
  helper  DmCms::PagesHelper
  helper  DmCms::CmsPagesHelper

  before_action :current_page, except: [:index, :file_tree, :expire_cache, :expire_cache_total]

  #------------------------------------------------------------------------------
  def index
    authorize! :access_content_section, :all
    CmsPage.create_default_site if CmsPage.roots.empty?
    # @tree = CmsPage.arrange(order: :position)
    @tree = CmsPage.includes(:translations).arrange(order: :row_order)
  end

  #------------------------------------------------------------------------------
  def new_page
    authorize! :manage_content, :all
    @cms_page = CmsPage.new
  end

  #------------------------------------------------------------------------------
  def create_page
    authorize! :manage_content, :all
    @cms_page = @current_page.children.new(cms_page_params)
    respond_to do |format|
      if @cms_page.save
        format.html { redirect_to admin_cms_page_url(@cms_page), notice: 'Page was successfully created.' }
        format.json { render json: @cms_page, status: :created, location: @cms_page }
      else
        format.html { render action: "new_page" }
        format.json { render json: @cms_page.errors, status: :unprocessable_entity }
      end
    end
  end

  #------------------------------------------------------------------------------
  def edit
    authorize! :manage_content, @current_page
    @cms_page = @current_page
  end

  #------------------------------------------------------------------------------
  def update
    authorize! :manage_content, @current_page
    if @current_page.update(cms_page_params)
      redirect_to action: :show, id: @current_page
    else
      @cms_page = @current_page
      render action: :edit
    end
  end

  #------------------------------------------------------------------------------
  def show
    authorize! :manage_content, @current_page
  end

  #------------------------------------------------------------------------------
  def mark_welcome_page
    authorize! :manage_content, :all
    @current_page.mark_as_welcome_page
    redirect_to action: :show, id: @current_page
  end

  #------------------------------------------------------------------------------
  def duplicate_page
    authorize! :manage_content, :all
    new_page = @current_page.duplicate_with_associations
    if new_page.nil?
      redirect_to admin_cms_page_url(@current_page), flash: { error: 'A duplicate page already exists' }
    else
      redirect_to edit_admin_cms_page_url(new_page), flash: { notice: 'Duplicate page created.  Please customize it.' }
    end
  end

  # Given a new parent_id and position, place item in proper place
  # Note that position comes in as 0-based, increment to make 1-based
  #------------------------------------------------------------------------------
  def ajax_sort
    @current_page.update(row_order_position: params[:item][:position], parent_id: params[:item][:parent_id]) if can? :manage_content, :all

    #--- this action will be called via ajax
    head :ok
  end

  #------------------------------------------------------------------------------
  def destroy
    authorize! :manage_content, :all
    @current_page.destroy
    redirect_to action: :index
  end

  # Removes all cache files for this account. This can be used when we're not sure if the
  # cache file for a changed page has been deleted or not
  #------------------------------------------------------------------------------
  def expire_cache
    #--- expire only items for this account
    key_start = combined_fragment_cache_key(Account.current.id)
    expire_fragment(%r{\A#{key_start.join('/')}})

    respond_to do |format|
      format.html { redirect_to({ action: :index }, notice: 'Page Cache was cleared') }
      format.js { head :ok }
    end
  end

  # Removes all cache files. This can be used when we're not sure if the
  # cache file for a changed page has been deleted or not
  #------------------------------------------------------------------------------
  def expire_cache_total
    expire_fragment(%r{\S})

    respond_to do |format|
      format.html { redirect_to({ action: :index }, notice: 'Page Cache for all sites cleared') }
      format.js { head :ok }
    end
  end

  #------------------------------------------------------------------------------
  def permissions
    authorize! :manage_content, :all
    if put_or_post? && (params[:user][:user_id])
      user = User.find(params[:user][:user_id])
      if user
        roles = params[:user].delete(:roles)
        [:manage_content].each do |role|
          roles[role].as_boolean ? user.add_role(role, @current_page) : user.remove_role(role, @current_page)
        end
        user.save!
      end
    end
    @content_managers = User.with_role(:content_manager)
    @content_managers_alacarte = User.with_role(:content_manager_alacarte)
  end

  #------------------------------------------------------------------------------
  def ajax_toggle_permission
    authorize! :manage_content, :all
    user = User.find(params[:user_id])
    role = params[:role].to_sym
    if user && [:manage_content].include?(role)
      user.has_role?(role, @current_page) ? user.remove_role(role, @current_page) : user.add_role(role, @current_page)
      user.save!
    end
    head :ok
  end

  protected

  #------------------------------------------------------------------------------
  def current_page
    @current_page = CmsPage.friendly.find(params[:id])
  end
end

cms/app/helpers/dm_cms/cms_pages_helper.rb
module DmCms::CmsPagesHelper
  #------------------------------------------------------------------------------
  def nested_tree(tree)
    tree.map do |item, sub_items|
      render(partial: 'tree', locals: { item: item, sub_items: sub_items })
    end.join.html_safe
  end

  #------------------------------------------------------------------------------
  def nested_tree_sidebar(tree)
    tree.map do |item, sub_items|
      render(partial: 'tree_sidebar', locals: { item: item, sub_items: sub_items })
    end.join.html_safe
  end

  # Return a list of templates defined in the theme.yml and it's parent theme.
  # The child templates should override any parent templates
  #------------------------------------------------------------------------------
  def template_menu_list
    theme = current_account.theme_data
    if theme.empty?
      nil
    else
      templates = (current_account.theme_data(parent: true)['templates'] || {}).merge(theme['templates'] || {})
      [['Inherit from parent', '']] + templates.collect { |key, value| [value['name'], key] }
    end
  end

  #------------------------------------------------------------------------------
  def template_name(search_for)
    template_item = template_menu_list&.detect { |x| x[1] == search_for }
    template_item ? template_item[0] : ''
  end
end

cms/app/views/dm_cms/admin/cms_pages/_content_toolbar.html.erb
<div class="pull-right">
  <% if contentitem_list.count > 1 %>
    <span class="sort_handle" style="margin-right: 10px;"></span>
  <% end %>
  <%= link_to icons(:edit), [:edit, :admin, contentitem], class: "btn btn-xs btn-default" %>
</div>

cms/app/views/dm_cms/admin/cms_pages/_form.html.erb
<% new_record = @cms_page.new_record? %>
<% content_for :content_title, @title %>
<% unless new_record %>
  <% content_for :content_title_extra do %>
    <%= page_header_buttons do %>
      <%= present(@cms_page).visibility %>
      <%= present(@cms_page).label_published %>
    <% end %>
  <% end %>
<% end %>

<% submit_url = (new_record ? create_page_admin_cms_page_path(@current_page) : admin_cms_page_path(@cms_page)) %>
<% title = (new_record ? "New Child Page " : "Edit Page Details ") %>
<%= simple_form_for @cms_page, url: submit_url, wrapper: :bs3_vertical_form, wrapper_mappings: DmAdmin::VerticalFormWrapperMappings do |f| %>

  <div class="row">
    <div class="col-md-8">
      <%= f.error_notification message: "Please review the problems below" %>
      <%= panel title: icon_label(:edit, title) do %>
        <%= locale_tabs do |locale| %>
          <%= f.input "title_#{locale}", label: 'Page Title', hint: 'The title of the page, shown in the browser title' %>
          <%= f.input "menutitle_#{locale}", label: 'Menu Title', hint: 'Text shown in a menu (which might be shorter than the full title).  If blank, page will not show up in any auto-generated menus' %>
        <% end %>

        <%= f.input :slug, label: 'Page Slug', hint: 'Leave blank to have auto-generated based on title' %>
      <% end %>

      <%= panel title: icon_label(:text, 'Content/Redirect') do %>
        <p>For displaying blocks of content, you can choose a template to use.</p>
        <p>If you wish to redirect to another page/link, then fill in the <em>Link</em> field.</p>
        <hr>
        <% templates = template_menu_list %>
        <% if templates %>
          <%= f.input :template, label: 'Template to Use', collection: templates, include_blank: false,
                  hint: 'Template to use for this page. Child pages can inherit this template' %>
        <% else %>
          <%= f.input :template, label: 'Template to Use', hint: "Leave blank to inherit the parent's template" %>
        <% end %>
        <hr>
        <%= f.input :link, label: 'Redirect To', hint: "Setting this field will <strong>always</strong> redirect to another page. Examples:<br>
        Slug: <em>my-other-page</em><br>
        Relative url: <em>blog/recent_posts</em><br>
        External url: <em>http://www.apple.com</em><br>
        Note: it's better to use a <em>slug</em> or <em>relative url</em> when possible".html_safe %>
        <hr>
        <%= f.input :preferred_open_in_new_window, as: :boolean, inline_label: 'Open page/url in a new window' %>
        <%= f.input :preferred_divider, as: :boolean, inline_label: 'Show as a divider in menu',
                hint: 'Only use this when you need a divider shown in the auto-generated menus - no content will be displayed.
                <em>This option may not be supported by your theme</em>'.html_safe %>

        <% if false #--- disable this for now %>
          <%= f.input :menuimage, label: 'Menu Image' %>
        <% end %>

      <% end %>


      <%= panel title: icon_label(:social_media, 'Social Media') do %>
        <%= f.input :preferred_show_social_buttons, as: :boolean, inline_label: 'Show social buttons', hint: 'Show the standard Facebook/Twitter buttons on the page' %>
        <div class="row">
          <div class="col-md-6">
            <%= f.input :featured_image, label: 'Featured Image', hint: 'Image used if page is liked on facebook.  Will not display on the page' %>
          </div>
          <div class="col-md-6">
            <% if @current_page.featured_image.present? %>
              <img src="<%= site_asset_media_url(@current_page.featured_image) %>" class="img-thumbnail img-responsive" style="margin-bottom: 20px;">
            <% end %>
          </div>
        </div>
        <%= locale_tabs do |locale| %>
          <%= f.input "summary_#{locale}", label: 'Page Summary', as: :code_editor, autoheight: true, input_html: {class: "CodeMirror-autoheight"},
                 hint: 'Text used when a page is liked on Facebook.  Is not visible on the page'%>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-4">
      <%= panel title: icon_label(:calendar, 'Publish') do %>
        <%= f.input :published, inline_label: 'Publish It?' %>
        <%= f.input :requires_login, inline_label: 'Requires Login?', hint: 'Page will require user to be logged in to access' %>
      <% end %>

      <%= submit_or_cancel save: new_record ? 'Create' : 'Update', cancel_url: submit_url %>
      <hr>

      <%= panel title: icon_label(:tags, 'Tags') do %>
        <%= f.input :tag_list, collection: CmsPage.tag_list_all, input_html: {multiple: '1', class: 'tag_field', } %>
      <% end %>

      <%= panel title: icon_label(:image, 'Header Image') do %>
        <% if @current_page.header_image.present? %>
          <img src="<%= site_asset_media_url(@current_page.header_image) %>" class="img-thumbnail img-responsive">
          <hr>
        <% end %>
        <%= f.input :header_image, label: 'Header Image', id: 'image_error', hint: 'Image used as a header/banner image, if supported by theme' %>
        <%= f.input :preferred_header_accent_color, as: :color_picker, label: 'Accent Color', hint: 'Accent color used in header (if supported by theme). Any valid CSS color' %>
      <% end %>
    </div>
  </div>
<% end %>

cms/app/views/dm_cms/admin/cms_pages/_tree.html.erb
<% open_or_closed = sub_items.blank? ? '' : (cookies["page_tree_#{item.id}"] ? 'tree_open' : 'tree_closed') %>
<li data-item_id="<%= item.id %>" class="<%= 'root' if item.is_root? %> <%= open_or_closed %>" >
  <dl>
    <dt>
      <% if !item.is_root? %>
        <a href="#" class="tree_expand"></a>
      <% end %>
      <% if item.divider? %>
        <% item_title = "&mdash; #{item.menutitle} &mdash;".html_safe %>
        <%= can?(:manage_content, item) ? link_to(item_title, :action => :show, :id => item) : item_title %>
      <% else %>
        <% item_title = (item.title.blank? ? item.slug : item.title) %>
        <%= can?(:manage_content, item) ? link_to(item_title, :action => :show, :id => item) : item_title %>
        <%= "  <span class='fa fa-globe'></span>".html_safe if item.welcome_page? %>
      <% end %>
    </dt>
    <dd><%= present(item).label_published %></dd>
    <dd>
      <%= link_to "New Child", new_page_admin_cms_page_path(item) if can? :manage_content, :all %>
    </dd>
  </dl>
  <%= (sub_items.blank? ? '' : content_tag(:ul, nested_tree(sub_items), :class => 'sub_tree', :style => ((item.is_root? || open_or_closed == 'tree_open') ? '' : 'display:none'))) %>
</li>

cms/app/views/dm_cms/admin/cms_pages/_tree_sidebar.html.erb
<li class="tree_item">
  <% if item.divider? %>
    <%= link_to "&mdash; #{item.menutitle} &mdash;".html_safe, :action => :show, :id => item %>
  <% else %>
    <%= link_to (item.title.blank? ? item.slug : item.title), :action => :show, :id => item %>
  <% end %>
  <%= (sub_items.blank? ? '' : content_tag(:ul, nested_tree_sidebar(sub_items), :class => 'arrow-list')) %>
</li>

cms/app/views/dm_cms/admin/cms_pages/edit.html.erb
<% content_for :content_title, present(@current_page).admin_edit_title %>
<%= render :partial => 'form' %>

cms/app/views/dm_cms/admin/cms_pages/index.html.erb
<% content_for :content_title, icon_label(:pages, 'Pages') %>
<% content_for :content_title_extra do %>
  <%= page_header_buttons do %>
    <%= link_to('Snippets', dm_cms.admin_cms_snippets_path, class: 'btn btn-default btn-sm') if can? :manage_content, :all %>
    <div class="btn-group">
      <button class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown"><%= icons(:cog) %> <span class="caret"></span></button>
      <ul class="dropdown-menu dropdown-menu-right">
        <li><%= link_to icon_label(:refresh, 'Clear Page Cache'), admin_expire_cache_path, method: :patch %></li>
      </ul>
    </div>
  <% end %>

<% end %>

<% if !current_account.preferred_site_enabled? %>
  <div class="alert alert-warning">
    Site is currently disabled - all requests will be sent to &#x27;Coming Soon&#x27; page unless logged in
  </div>
<% end %>

<%= panel header: false do %>
  <ul id="tree_sort" data-update_url="<%= dm_cms.admin_cms_page_sort_path %>">
    <%= nested_tree(@tree) %>
  </ul>
<% end %>

cms/app/views/dm_cms/admin/cms_pages/new_page.html.erb
<% content_for :content_title, 'New Child Page for: '.html_safe + present(@current_page).admin_edit_title %>
<%= render :partial => 'form' %>

cms/app/views/dm_cms/admin/cms_pages/permissions.html.erb
<% content_for :content_title, "Permissions" %>
<% content_for :content_subtitle, "#{@current_page.title}" %>

<div class="row">
  <div class="col-md-8">
    <%= panel body: false, title: "Permissions" do %>
      <div class="panel-body">
        <p>The users below can be granted access to this particular page.</p>

        <% @content_managers_alacarte.each do |user| %>
          <div class="row">
            <div class="col-md-12">
              <%= subsection title: user.full_name do %>
                <% manage_content_state = user.has_role?(:manage_content, @current_page) ? 'btn-success active' : 'btn-default' %>
                <%= link_to 'Page Editing',     dm_cms.ajax_toggle_permission_admin_cms_page_path(@current_page, user.id, :manage_content), class: "permission_btn btn btn-sm #{manage_content_state}", role: 'button', remote: true, method: :patch %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

    <% end %>
  </div>
  <div class="col-md-4">
    <%= subsection title: "Content Managers" do %>
      <p>Current users that can fully manage pages</p>

      <table class="table table-bordered table-condensed table-striped">
        <tbody>
          <% @content_managers.each do |user| %>
            <tr>
              <td><%= user.full_name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
<script>
$(document).ready(function() {
  $('.permission_btn').on("ajax:success", function(e, content) {
    if ($(this).is(".active")) {
      $(this).addClass("btn-default");
      $(this).removeClass("active").removeClass("btn-success");
    } else {
      $(this).addClass("active").addClass("btn-success");
      $(this).removeClass("btn-default");
    }
  });
});
</script

cms/app/views/dm_cms/admin/cms_pages/show.html.erb
<% content_for :content_title, present(@current_page).admin_edit_title %>
<% content_for :content_title_extra do %>
  <%= page_header_buttons do %>
    <%= present(@current_page).visibility %>
    <%= present(@current_page).label_published %>
    <% if @current_page.content_page? %>
      <%= link_to icon_label(:new, 'Add Content'), new_content_admin_cms_contentitem_path(@current_page), title: 'Add Content Block', class: 'btn btn-sm btn-default' %>
    <% end %>
    <%= link_to icons(:view), url_for("/#{current_account.preferred_default_locale}/#{@current_page.slug}"), title: 'View Page', class: 'btn btn-sm btn-default', target: '_blank' %>
    <%= link_to(icons(:edit),  [:edit, :admin, @current_page], class: "btn btn-sm btn-default", title: 'Edit') %>
    <% if can?(:manage_content, :all) %>
      <div class="btn-group">
        <button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown"><%= icons(:cog) %> <span class="caret"></span></button>
        <ul class="dropdown-menu dropdown-menu-right icons-right">
          <li><%= link_to icon_label(:lock, 'Permissions'), permissions_admin_cms_page_path(@current_page) %></li>
          <li><%= link_to icon_label(:globe, "#{'Un-' if @current_page.welcome_page?}Mark Welcome Page"), mark_welcome_page_admin_cms_page_path(@current_page), method: :patch %></li>
          <li><%= link_to icon_label(:facebook, 'Clear Facebook Cache'), "https://developers.facebook.com/tools/debug/og/object?q=#{ERB::Util.url_encode(dm_cms.showpage_url(@current_page.slug))}",
                 target: '_blank' %></li>
          <% if can?(:manage_content, :all) && !@current_page.new_record? %>
            <li class="divider"></li>
            <li class="text-danger"><%= link_to icon_label(:delete, 'Delete Page', icon_class: 'text-danger', label_class: 'text-danger'), [:admin, @current_page], method: :delete, class: 'text-danger', data: {confirm: 'Are you sure you wish to delete this page?'} %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-9">
    <% if @current_page.content_page? %>
      <div id="drag_sort" class="admin_blog_list" data-update_url="<%= dm_cms.admin_cms_contentitem_sort_path %>">
        <% @current_page.cms_contentitems.each do |item| %>
          <% toolbar = render partial: 'content_toolbar', locals: { contentitem: item,  contentitem_list: @current_page.cms_contentitems } %>
          <div class="item" data-item_id="<%= item.id %>">
            <%= panel title: "#{item.container}", body: false, toolbar: toolbar do %>
              <pre class="prettyprint" style="border:none;border-bottom: 1px solid #eee;">
<%= truncate(item.send("content_#{current_account.preferred_default_locale}"), length: 250) %>
              </pre>
              <span class="subtitle text-muted text-center">Format: <%= item.itemtype %></span>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <% if @current_page.redirect_page? %>
        <%= panel title: @current_page.pagetype_name, body: true do %>
          <p>This page will automatically re-direct to another internal/external page.</p>
          <dl class="dl-horizontal">
            <dt>Specified URL</dt>
            <dd><%= @current_page.link %></dd>
            <dt>Will Redirect To</dt>
            <dd>
              <%= link_to redirect_link(@current_page.link), redirect_link(@current_page.link), target: '_blank' %>
              <% if @current_page.preferred_open_in_new_window? %>
                (will open in new window)
              <% end %>
            </dd>
          </dl>
        <% end %>
      <% elsif @current_page.divider? %>
        <%= panel title: @current_page.pagetype_name, body: true do %>
          <p>This is used simply as a placeholder page that will generate a "divider" item in the menu.  It does not have any real content.</p>
        <% end %>
      <% end %>
      <% unless @current_page.cms_contentitems.empty? %>
        <div class="alert alert-warning">
          <p>This page contains <%= @current_page.cms_contentitems.count %> content blocks that will not be shown.</p>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-3">
    <% if @current_page.header_image.present? || @current_page.tag_list.count > 0 %>
      <% if @current_page.header_image.present? %>
        <img src="<%= site_asset_media_url(@current_page.header_image) %>" class="img-thumbnail img-responsive">
      <% end %>
      <% if @current_page.tag_list.count > 0 %>
        <div class="tag_list" style="margin-top: 10px;">
          <% @current_page.tag_list.each do |tag| %>
            <% active_tag = (@tag_filter == tag ? 'active' : '') %>
            <%= link_to content_tag(:span, tag, class: "tag #{active_tag}"), edit_admin_cms_page_path(@current_page) %>
          <% end %>
        </div>
        <% end %>
      <hr>
    <% end %>

    <%= subsection title: 'Attributes' do %>
      <dl class="infolist">
        <dt class="text-info">Slug</dt>
        <dd><%= @current_page.slug %></dd>
        <dt class="text-info"></dt>
        <dt class="text-info">Type</dt>
        <dd>
          <%= @current_page.pagetype_name %>
        </dd>
        <dt class="text-info">Template</dt>
        <dd>
          <% if @current_page.template.blank? %>
            <%= label_icon(template_name(@current_page.page_template), 'fa fa-arrow-up') %> <small>(inherited)</small>
          <% else %>
            <%= template_name(@current_page.page_template) %>
          <% end %>
        </dd>
        <dt class="text-info">Menu Title</dt>
        <dd><%= !@current_page.menutitle.blank? ? @current_page.menutitle : '<em>Will not be shown in menus</em>'.html_safe %></dd>
      </dl>
    <% end %>
  </div>
</div>